[Rainmeter]
Author=Bridget512

[Variables]
FontName=EXO
FontColor=255,255,255,240
TitleSize=20
TextSize=10
GraphLine=250,250,250,60
StringAlign=RIGHT
StringCase=LOWER

===========================

[Title]
SolidColor=0,0,0,1
StringCase=LOWER

[Meter-FREE]
SolidColor=0,0,0,1

[BackgroundColor]
SolidColor=255,255,255,1

===========================

[ActivityGraph]
X=134
Y=5
W=42
H=25
LineWidth=1
LineColor=#GraphLine#
AntiAlias=1

[ActivityGraph_RAM]
X=126
Y=5
W=50
H=25
LineWidth=1
LineColor=#GraphLine#
AntiAlias=1
